/**
 * The initial values for the redux state.
 */
export const INITIAL_STATE = {
  checkInId: null,
  checkIn: {},
  checkIns: [],
  emotions: [
    { name: 'Anger', color: '#d92120', selected: false },
    { name: 'Rage', color: '#dd3023', selected: false },
    { name: 'Exasperated', color: '#e14126', selected: false },
    { name: 'Irritable', color: '#e35229', selected: false },
    { name: 'Envy', color: '#e6622c', selected: false },
    { name: 'Disgust', color: '#e7722f', selected: false },
    { name: 'Sadness', color: '#e78031', selected: false },
    { name: 'Suffering', color: '#e68c34', selected: false },
    { name: 'Depressed', color: '#e49836', selected: false },
    { name: 'Disappointed', color: '#e1a138', selected: false },
    { name: 'Shameful', color: '#dca93b', selected: false },
    { name: 'Neglected', color: '#d7af3d', selected: false },
    { name: 'Despair', color: '#d0b540', selected: false },
    { name: 'Surprise', color: '#c9b843', selected: false },
    { name: 'Shocked', color: '#c1bb46', selected: false },
    { name: 'Confused', color: '#b8bd4a', selected: false },
    { name: 'Amazed', color: '#aebe4f', selected: false },
    { name: 'Astounded', color: '#a5be54', selected: false },
    { name: 'Moved', color: '#9bbe5a', selected: false },
    { name: 'Joy', color: '#91bd61', selected: false },
    { name: 'Content', color: '#88bb69', selected: false },
    { name: 'Happy', color: '#7fb972', selected: false },
    { name: 'Cheerful', color: '#76b67c', selected: false },
    { name: 'Proud', color: '#6eb387', selected: false },
    { name: 'Optimistic', color: '#66af93', selected: false },
    { name: 'Hopeful', color: '#5faa9f', selected: false },
    { name: 'Elation', color: '#59a5ab', selected: false },
    { name: 'Enchanted', color: '#539eb5', selected: false },
    { name: 'Love', color: '#4e97bd', selected: false },
    { name: 'Affection', color: '#4a8ec1', selected: false },
    { name: 'Longing', color: '#4684c2', selected: false },
    { name: 'Passion', color: '#4379be', selected: false },
    { name: 'Tenderness', color: '#416db7', selected: false },
    { name: 'Peaceful', color: '#3f60ae', selected: false },
    { name: 'Sensitive', color: '#3f53a4', selected: false },
    { name: 'Fear', color: '#40459a', selected: false },
    { name: 'Helpless', color: '#413891', selected: false },
    { name: 'Terror', color: '#452c89', selected: false },
    { name: 'Worried', color: '#4b2183', selected: false },
    { name: 'Insecure', color: '#541a7f', selected: false },
    { name: 'Anxious', color: '#62187e', selected: false },
    { name: 'Dread', color: '#781c81', selected: false },
  ],
  checkInIsLoading: false,
  checkInErrorMessage: null,
}
